### ISSUE TITLE
Method fit_psds not working with lmfit 0.9.11 and pyotic 0.12.0

### ISSUE THREAD

**Issue by KevinStrobel** [cellular-nanoscience/pyotic#5] opened 2018-10-23 11:47 UTC
Execution of method ``fit_psds`` in a height calibration is not working any more with the newest lmfit version.

Works with:
- lmfit 0.9.5 & 0.9.7
- pyotic 0.11.4

Error with:
- lmfit (0.9.11)
- pyotic (0.12.0)

#### Code Sample

```python

# import pyotc Height Calibration object
from pyotc.height_calibration import HeightCalibration

hc = HeightCalibration()

basename = 'B01_'
directory = '../calibration/converted_data/'

hc.get_psd_files(basename, directory=directory);

# bounds = {'x': (10, 20e3), 'y': (10, 20e3), 'z': (10, 4e3)}
# bounds = (1, 45e3)
bounds = None

# f_ex = {'x': [12, 88], 'y': [8, 48, 52], 'z': [48]}
f_ex = None

hc.gen_psd_fits(bounds=bounds, f_exclude=f_ex)

# hc.add_height_offset(offset, unit='um')
hc.setup_psd_fits(model='hydro', dynamic=False)

heights = None  # fit at all heights
#heights = 0.52  # height or list of heights to fit

names = None  # fit all axes
#names = ['x']  # name or list of names to fit

kwargs = {}
#kwargs = {'f_c': 10e3}  # initial guess values for the fit

# set boundaries of data to be fitted 
bounds={'x': (200, 40e3), 'y': (200, 40e3), 'z': (200, 6e3)}
f_exclude={'x': [], 'y': [], 'z':[]}

hc.fit_psds(heights=heights, names=names, fitreport=0, plot_fits=True, plot_delay=0.0, dynamic_bounds=False,
            bounds=bounds, f_exclude=f_exclude, use_heights=False, save_plots=True, **kwargs)

hc.plot_pc_results()
```
#### Problem description

```python

---------------------------------------------------------------------------
 TypeError                                 Traceback (most recent call last)
 <ipython-input-4-26d8019a3553> in <module>()
      13 
      14 hc.fit_psds(heights=heights, names=names, fitreport=0, plot_fits=True, plot_delay=0.0, dynamic_bounds=False,
 ---> 15             bounds=bounds, f_exclude=f_exclude, use_heights=False, save_plots=True, **kwargs)
      16 
      17 hc.plot_pc_results()

 /usr/local/lib/python3.6/dist-packages/pyotc/height_calibration.py  in fit_psds(self, heights, names, dynamic_bounds, bounds, f_exclude,  use_heights, fitreport, plot_fits, plot_delay, plot_axis, figsize,  save_plots, save_as, directory, basename, verbose, plot_kws, **kwargs)
    1755                                           fitreport=fitreport,
    1756                                           verbose=verbose,
 -> 1757                                           **kwargs)
    1758             if plot_fits:
    1759                 plot_axis.cla()

 /usr/local/lib/python3.6/dist-packages/pyotc/psd_fitting.py  in fit_psds(self, names, dynamic_bounds, bounds, f_exclude,  use_heights, calc_results, plot_fits, plot_axis, fitreport, verbose,  **kwargs)
    1801                          fitreport=fitreport,
    1802                          verbose=verbose,
 -> 1803                          **kwargs)
    1804             if calc_results:
    1805                 self.calc_pc_results(names=name, verbose=verbose)

 /usr/local/lib/python3.6/dist-packages/pyotc/psd_fitting.py  in fit_psd(self, name, dynamic_bounds, bounds, f_exclude, use_heights,  plot_fit, plot_axis, plot_masked_data, fitreport, verbose, **kwargs)
    1665                            N_avg=N_avg,
    1666                            verbose=verbose,
 -> 1667                            **kwargs)
    1668 
    1669         modelname = modelfit.model.name.replace('Model(', '').replace(')', '')

 /usr/local/lib/python3.6/dist-packages/pyotc/psd_fitting.py  in fit_psd(freq, psd_data, psd_err, N_avg, model, lp_filter, lp_fixed,  aliasing, f_sample, N_alias, model_fun, name, verbose, **kwargs)
     291     modelfit = model_obj.fit(1/psd_data, freq=freq,
     292                              params=pars, weights=weights,
 --> 293                              fit_kws={'nan_policy': 'propagate'})
     294     if verbose:
     295         report_fit(modelfit)

 /usr/lib/python3/dist-packages/lmfit/model.py  in fit(self, data, params, weights, method, iter_cb, scale_covar,  verbose, fit_kws, nan_policy, **kwargs)
     870         output = ModelResult(self, params, method=method, iter_cb=iter_cb,
     871                              scale_covar=scale_covar, fcn_kws=kwargs,
 --> 872                              nan_policy=self.nan_policy, **fit_kws)
     873         output.fit(data=data, weights=weights)
     874         output.components = self.components

​
```

#### Expected Output

```python
# Matplotlib plots 

```

#### Output of ``pip3 list``

<details>

INSTALLED VERSIONS
------------------
alabaster (0.7.8)
alembic (1.0.0.dev0)
AllanTools (2018.3)
appdirs (1.4.3)
asn1crypto (0.24.0)
asteval (0.9.12)
astroid (2.0.4)
async-generator (1.9)
atomicwrites (1.1.5)
attrs (18.2.0)
Babel (2.6.0)
beautifulsoup4 (4.6.3)
bleach (2.1.3)
blosc (1.5.1)
Bottleneck (1.2.1)
bqplot (0.11.1)
Brlapi (0.6.7)
BTrees (4.3.1)
certifi (2018.8.24)
cftime (1.0.1)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
cloudpickle (0.5.6)
colorama (0.3.7)
cryptography (2.3)
cupshelpers (1.0)
cycler (0.10.0)
Cython (0.28.4)
dask (0.17.5)
decorator (4.3.0)
distro (1.3.0)
docutils (0.14)
entrypoints (0.2.3.post3)
GDAL (2.3.2)
gitdb2 (2.0.4)
GitPython (2.1.11)
h5py (2.8.0)
html5lib (1.0.1)
httplib2 (0.11.3)
idna (2.6)
imageio (2.4.1)
imagesize (1.0.0)
ipykernel (4.9.0)
ipyleaflet (0.9.1)
ipympl (0.2.1)
ipython (5.8.0)
ipython-genutils (0.2.0)
ipywidgets (7.4.2)
isort (4.3.4)
jedi (0.12.0)
Jinja2 (2.10)
joblib (0.12.3)
jsonschema (2.6.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
jupyterhub (0.9.4)
jupyterlab (0.35.2)
jupyterlab-latex (0.4.1)
jupyterlab-launcher (0.13.1)
jupyterlab-server (0.2.0)
keyring (15.1.0)
keyrings.alt (3.1)
kiwisolver (1.0.1)
lazy-object-proxy (1.3.1)
lmfit (0.9.11)
locket (0.2.0)
logilab-common (1.4.1)
louis (3.7.0)
lxml (4.2.5)
Mako (1.0.7)
MarkupSafe (1.0)
matplotlib (2.2.2)
mccabe (0.6.1)
mistune (0.8.4)
more-itertools (4.2.0)
mpmath (1.0.0)
nbconvert (5.3.1)
nbdime (1.0.3)
nbformat (4.4.0)
netCDF4 (1.4.1)
networkx (2.1)
nfft (0.1)
nose (1.3.7)
notebook (5.4.1)
numexpr (2.6.8)
numpy (1.14.5)
numpydoc (0.7.0)
olefile (0.46)
packaging (18.0)
pamela (0.3.0)
pandas (0.23.3)
pandocfilters (1.4.2)
parso (0.2.1)
partd (0.3.8)
patsy (0.4.1+dev)
persistent (4.4.2)
pexpect (4.6.0)
pickleshare (0.7.5)
Pillow (5.3.0)
PIMS (0.4.1)
Pint (0.8.1)
pip (9.0.1)
pluggy (0.6.0)
prometheus-client (0.2.0)
prompt-toolkit (1.0.15)
psutil (5.4.6)
py (1.6.0)
pycairo (1.16.2)
pycodestyle (2.4.0)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0.1)
pyflakes (1.6.0)
Pygments (2.2.0)
PyGObject (3.30.1)
pylint (2.1.1)
pyNFFT (1.3.2)
pyotic (0.12.2)
pyparsing (2.2.0)
pysmbc (1.0.15.6)
pytest (3.6.4)
python-apt (1.7.0)
python-dateutil (2.6.1)
python-debian (0.1.33)
python-debianbts (2.7.2)
python-editor (1.0.3)
python-oauth2 (1.1.0)
pytz (2018.5)
PyWavelets (0.5.1)
pyxdg (0.25)
PyYAML (3.12)
pyzmq (17.1.0)
QtAwesome (0.4.4)
qtconsole (4.3.1)
QtPy (1.3.1)
reportbug (7.5.0)
reportlab (3.5.9)
requests (2.18.4)
roman (2.0.0)
rope (0.10.5)
scikit-image (0.14.1)
scikit-learn (0.19.2)
scipy (1.1.0)
scour (0.37)
seaborn (0.8.0)
SecretStorage (2.3.1)
Send2Trash (1.4.2)
setuptools (40.4.3)
Shapely (1.6.4)
simplegeneric (0.8.1)
simplejson (3.15.0)
six (1.11.0)
slicerator (0.9.8)
smmap2 (2.0.4)
Sphinx (1.7.9)
spyder (3.2.6)
SQLAlchemy (1.2.8)
sudospawner (0.5.1)
sympy (1.3)
tables (3.4.4)
terminado (0.8.1)
testpath (0.4.2)
tifffile (2018.10.18)
toolz (0.9.0)
tornado (5.1.1)
trackpy (0.4.1)
traitlets (4.3.2)
traittypes (0.0.6)
transaction (2.3.0)
unattended-upgrades (0.1)
uncertainties (3.0.2)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5)
wheel (0.30.0)
widgetsnbextension (3.4.2)
wrapt (1.10.11)
xarray (0.10.7)
zc.lockfile (1.3.0)
ZConfig (3.1.0)
ZODB (5.5.0)
zodbpickle (1.0.2)
zope.interface (4.3.2)

</details>

**Comment by stevosn** [comment] 2018-10-24 11:49
Thanks kevin! 
This is a duplicate of #4. And solved with version 0.12.2. Closed

**Closed as completed by stevosn** 2018-10-24 11:49 UTC
Labels: duplicate
